### ISSUE TITLE
GPI lib won't build after Ubuntu 16.04 update

### ISSUE THREAD

**Issue by snakemastr** [CasparCG/client#231]
Worked on Caspar Client on Ubuntu 14.04, all good.
Updated to Ubuntu 16.04 and now my project won't build. 
Error:
/Gpi/libgpi.so:-1: error: undefined reference to `gpio::serial_port_device::create(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, boost::function<void (bool)> const&)'

Any thoughts on this? I have no clue, nothing was changed in the project sinds the update..

**Comment by dimitry-ishenko** [comment]
This is because gcc 5 builds with c++11 ABI enabled by default. You either need to recompile libgpio with gcc >= 5. Or alternatively, compile your project with gcc < 5 (eg 4.9.4).

**Comment by dotarmin** [comment]
@snakemastr, did @dimitry-ishenko answer help you make it work again?

**Comment by dimitry-ishenko** [comment]
Running into same issue here... It seems the solution is to `#define _GLIBCXX_USE_CXX11_ABI=0` to force gcc to use pre c++11 ABI

**Comment by dimitry-ishenko** [comment]
@snakemastr FYI

**Comment by Julusian** [comment]
The build process has been reworked so this no longer applies
